SiteProfss_v01/Controllers/dbd_EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SiteProfss_v01.Models.DB;
using SiteProfss_v01.Models.Clases;
using System.Net;
using System.Data.Entity;

namespace SiteProfss_v01.Controllers
{
    public class dbd_EmpresaController : Controller
    {
        private DB_SiteProfss db = new DB_SiteProfss();

        // GET: dbdEmpresa
        public ActionResult Index()
        {
            return View();
        }


        // GET: Ofertas/Create
        public ActionResult CrearOferta()
        {
            ViewBag.CategoriaId = new SelectList(db.Categorias, "Id", "NombreCategoria");
            ViewBag.DepartamentoId = new SelectList(db.Departamentos, "Id", "NombreDepartamento");
            ViewBag.TiempoContratacionId = new SelectList(db.TiemposContratacion, "Id", "Descripcion");
            return View();
        }

        // POST: Ofertas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CrearOferta([Bind(Include = "Id,Titulo,Descripcion,AreaLaboral,CantidadVacantes,HabilidadesRequeridas,EdadDesde,EdadHasta,Remuneracion,TransporteRecorrido,FechaLimiteSolicitud,CategoriaId,DepartamentoId,TiempoContratacionId")] vmOferta vmOferta)
        {
            if (ModelState.IsValid)
            {
                Oferta oOferta = new Oferta
                {
                    Titulo = vmOferta.Titulo,
                    Descripcion = vmOferta.Descripcion,
                    FechaPublicacion = DateTime.Now,
                    AreaLaboral = vmOferta.AreaLaboral,
                    CantidadVacantes = vmOferta.CantidadVacantes,
                    HabilidadesRequeridas = vmOferta.HabilidadesRequeridas,
                    EdadDesde = vmOferta.EdadDesde,
                    EdadHasta = vmOferta.EdadHasta,
                    Remuneracion = vmOferta.Remuneracion,
                    TransporteRecorrido = vmOferta.TransporteRecorrido,
                    FechaLimiteSolicitud = vmOferta.FechaLimiteSolicitud,
                    Anulada = false,
                    EmpresaId = db.Usuarios.FirstOrDefault(u => u.Email == User.Identity.Name).Id,
                    CategoriaId = vmOferta.CategoriaId,
                    DepartamentoId = vmOferta.DepartamentoId,
                    TiempoContratacionId = vmOferta.TiempoContratacionId

                };

                db.Ofertas.Add(oOferta);
                db.SaveChanges();
                return RedirectToAction("ListarOfertasEmpresa", new { pEmpresaId = oOferta.EmpresaId });
            }

            ViewBag.CategoriaId = new SelectList(db.Categorias, "Id", "NombreCategoria", vmOferta.CategoriaId);
            ViewBag.DepartamentoId = new SelectList(db.Departamentos, "Id", "NombreDepartamento", vmOferta.DepartamentoId);
            ViewBag.TiempoContratacionId = new SelectList(db.TiemposContratacion, "Id", "Descripcion", vmOferta.TiempoContratacionId);
            return View(vmOferta);
        }

        public ActionResult EditarOferta(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Oferta oOferta = db.Ofertas.Find(id);
            if (oOferta == null)
            {
                return HttpNotFound();
            }

            vmOferta vmOferta = new vmOferta
            {
                Id = oOferta.Id,
                Titulo = oOferta.Titulo,
                Descripcion = oOferta.Descripcion,
                AreaLaboral = oOferta.AreaLaboral,
                CantidadVacantes = oOferta.CantidadVacantes,
                HabilidadesRequeridas = oOferta.HabilidadesRequeridas,
                EdadDesde = oOferta.EdadDesde,
                EdadHasta = oOferta.EdadHasta,
                Remuneracion = oOferta.Remuneracion,
                TransporteRecorrido = oOferta.TransporteRecorrido,
                FechaLimiteSolicitud = oOferta.FechaLimiteSolicitud,

            };

            ViewBag.CategoriaId = new SelectList(db.Categorias, "Id", "NombreCategoria", vmOferta.CategoriaId);
            ViewBag.DepartamentoId = new SelectList(db.Departamentos, "Id", "NombreDepartamento", vmOferta.DepartamentoId);
            ViewBag.TiempoContratacionId = new SelectList(db.TiemposContratacion, "Id", "Descripcion", vmOferta.TiempoContratacionId);

            return View(vmOferta);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarOferta([Bind(Include = "Id,Titulo,Descripcion,AreaLaboral,CantidadVacantes,HabilidadesRequeridas,EdadDesde,EdadHasta,Remuneracion,TransporteRecorrido,FechaLimiteSolicitud,CategoriaId,DepartamentoId,TiempoContratacionId")] vmOferta vmOferta)
        {
            if (ModelState.IsValid)
            {
                Oferta oOferta = db.Ofertas.Find(vmOferta.Id);
                oOferta.Titulo = vmOferta.Titulo;
                oOferta.Descripcion = vmOferta.Descripcion;
                oOferta.AreaLaboral = vmOferta.AreaLaboral;
                oOferta.CantidadVacantes = vmOferta.CantidadVacantes;
                oOferta.HabilidadesRequeridas = vmOferta.HabilidadesRequeridas;
                oOferta.EdadDesde = vmOferta.EdadDesde;
                oOferta.EdadHasta = vmOferta.EdadHasta;
                oOferta.Remuneracion = vmOferta.Remuneracion;
                oOferta.TransporteRecorrido = vmOferta.TransporteRecorrido;
                oOferta.FechaLimiteSolicitud = vmOferta.FechaLimiteSolicitud;
                oOferta.CategoriaId = vmOferta.CategoriaId;
                oOferta.DepartamentoId = vmOferta.DepartamentoId;
                oOferta.TiempoContratacionId = vmOferta.TiempoContratacionId;

                db.Entry(oOferta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListarOfertasEmpresa", new { pEmpresaId = oOferta.EmpresaId });
            }
            ViewBag.CategoriaId = new SelectList(db.Categorias, "Id", "NombreCategoria", vmOferta.CategoriaId);
            ViewBag.DepartamentoId = new SelectList(db.Departamentos, "Id", "NombreDepartamento", vmOferta.DepartamentoId);
            ViewBag.TiempoContratacionId = new SelectList(db.TiemposContratacion, "Id", "Descripcion", vmOferta.TiempoContratacionId);
            return View(vmOferta);
        }

        public ActionResult ListarOfertasEmpresa(int pEmpresaId)
        {
            var lstOfertas = (db.Ofertas.Where(o => o.EmpresaId == pEmpresaId).Select(o => o).OrderBy(o => o.FechaPublicacion).Include(o => o.Categoria).Include(o => o.Departamento).Include(o => o.TiempoContratacion)).ToList();
            var lstvmOfertas = new List<vmOferta>();
            foreach (Oferta o in lstOfertas)
            {
                lstvmOfertas.Add(new vmOferta
                {
                    Id = o.Id,
                    Titulo = o.Titulo,
                    Descripcion = o.Descripcion,
                    FechaPublicacion = o.FechaPublicacion,
                    AreaLaboral = o.AreaLaboral,
                    CantidadVacantes = o.CantidadVacantes,
                    HabilidadesRequeridas = o.HabilidadesRequeridas,
                    EdadDesde = o.EdadDesde,
                    EdadHasta = o.EdadHasta,
                    Remuneracion = o.Remuneracion,
                    TransporteRecorrido = o.TransporteRecorrido,
                    FechaLimiteSolicitud = o.FechaLimiteSolicitud,
                    Categoria = o.Categoria,
                    Departamento = o.Departamento,
                    TiempoContratacion = o.TiempoContratacion
                });
            }
            return View(lstvmOfertas);
        }

        // GET: Ofertas/Details/5
        public ActionResult DetallesOferta(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oferta oferta = db.Ofertas.Find(id);

            if (oferta == null)
            {
                return HttpNotFound();
            }
            return View(oferta);
        }

    }
}

       

SiteProfss_v01/Views/dbd_Empresa/CrearOferta.cshtml
@model SiteProfss_v01.Models.Clases.vmOferta

@{
    ViewBag.Title = "CrearOferta";
}


<div id="main">

    <h2>CrearOferta</h2>

    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
    
        <div class="form-horizontal">
            <h4>vmOferta</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AreaLaboral, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AreaLaboral, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AreaLaboral, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CantidadVacantes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CantidadVacantes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CantidadVacantes, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HabilidadesRequeridas, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HabilidadesRequeridas, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HabilidadesRequeridas, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EdadDesde, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EdadDesde, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EdadDesde, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EdadHasta, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EdadHasta, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EdadHasta, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Remuneracion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Remuneracion)
                        @Html.ValidationMessageFor(model => model.Remuneracion, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TransporteRecorrido, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.TransporteRecorrido)
                        @Html.ValidationMessageFor(model => model.TransporteRecorrido, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FechaLimiteSolicitud, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FechaLimiteSolicitud, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FechaLimiteSolicitud, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CategoriaId, "CategoriaId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CategoriaId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DepartamentoId, "DepartamentoId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("DepartamentoId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DepartamentoId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TiempoContratacionId, "TiempoContratacionId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("TiempoContratacionId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TiempoContratacionId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

</div>

SiteProfss_v01/Views/dbd_Empresa/DetallesOferta.cshtml
@model SiteProfss_v01.Models.DB.Oferta

@{
    ViewBag.Title = "DetallesOferta";
}

<div id="main">

    <h2>DetallesOferta</h2>

    <div>
        <h4>Oferta</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Categoria)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Categoria.NombreCategoria)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Departamento)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Departamento.NombreDepartamento)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TiempoContratacion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TiempoContratacion.Descripcion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Titulo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Titulo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Descripcion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Descripcion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FechaPublicacion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FechaPublicacion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AreaLaboral)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AreaLaboral)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CantidadVacantes)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CantidadVacantes)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HabilidadesRequeridas)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HabilidadesRequeridas)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.EdadDesde)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EdadDesde)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.EdadHasta)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EdadHasta)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Remuneracion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Remuneracion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TransporteRecorrido)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TransporteRecorrido)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FechaLimiteSolicitud)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FechaLimiteSolicitud)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Editar", "EditarOferta", new { id = Model.Id }) |
        @Html.ActionLink("Inicio", "Index")
    </p>

</div>

SiteProfss_v01/Views/dbd_Empresa/EditarOferta.cshtml
@model SiteProfss_v01.Models.Clases.vmOferta

@{
    ViewBag.Title = "EditarOferta";
}

<div id="main">

    <h2>EditarOferta</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
    
        <div class="form-horizontal">
            <h4>vmOferta</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AreaLaboral, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AreaLaboral, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AreaLaboral, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CantidadVacantes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CantidadVacantes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CantidadVacantes, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HabilidadesRequeridas, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HabilidadesRequeridas, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HabilidadesRequeridas, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EdadDesde, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EdadDesde, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EdadDesde, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EdadHasta, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EdadHasta, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EdadHasta, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Remuneracion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Remuneracion)
                        @Html.ValidationMessageFor(model => model.Remuneracion, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TransporteRecorrido, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.TransporteRecorrido)
                        @Html.ValidationMessageFor(model => model.TransporteRecorrido, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FechaLimiteSolicitud, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FechaLimiteSolicitud, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FechaLimiteSolicitud, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CategoriaId, "CategoriaId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CategoriaId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DepartamentoId, "DepartamentoId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("DepartamentoId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DepartamentoId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TiempoContratacionId, "TiempoContratacionId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("TiempoContratacionId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TiempoContratacionId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

</div>

SiteProfss_v01/Views/dbd_Empresa/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!-- Main -->
<div id="main">

    <!-- Intro -->
    <section id="top" class="one dark cover">

        <div class="container">

            <header>
                <h2 class="alt">
                    ¡Bienvenido a tu panel de administracion!
                </h2>
                <p>
                    Desde aqui podras realizar todo las opciones que<br />
                    SiteProfss te ofrece.
                </p>
            </header>

            <footer>
                <a href=@Url.Action("CrearOferta","dbd_Empresa") class="button scrolly">Crear Oferta</a>
            </footer>

        </div>
    </section>
</div>

SiteProfss_v01/Views/dbd_Empresa/L_Empresa.cshtml
@using SiteProfss_v01.Models.DB

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Empresa - SITEPROFSS</title>

    @Styles.Render("~/Content/dbs/css")

</head>
<body>


    <!-- Header -->
    <div id="header">

        <div class="top">

            @{
                Empresa oEmpresa;

                using (DB_SiteProfss db = new DB_SiteProfss())
                {
                    oEmpresa = (Empresa)db.Usuarios.FirstOrDefault(u => u.Email == User.Identity.Name);
                }

            }
            
            @Html.Partial("_NomEmpresaPartial", oEmpresa)            

            <!-- Nav -->
            <nav id="nav">
                <!--

                    Prologue's nav expects links in one of two formats:

                    1. Hash link (scrolls to a different section within the page)

                       <li><a href="#foobar" id="foobar-link" class="icon fa-whatever-icon-you-want skel-layers-ignoreHref"><span class="label">Foobar</span></a></li>

                    2. Standard link (sends the user to another page/site)

                       <li><a href="http://foobar.tld" id="foobar-link" class="icon fa-whatever-icon-you-want"><span class="label">Foobar</span></a></li>

                -->
                <ul>
                    <li><a href=@Url.Action("Index", "dbd_Empresa") id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-home">Inicio</span></a></li>
                    <li><a href="@Url.Action("ListarOfertasEmpresa", "dbd_Empresa", new { pEmpresaId = oEmpresa.Id } )" id="portfolio-link" class="skel-layers-ignoreHref"><span class="icon fa-th">Mis Ofertas</span></a></li>
                    <li><a href="#about" id="about-link" class="skel-layers-ignoreHref"><span class="icon fa-user">Actualizar Perfil</span></a></li>
                    <li><a href="#contact" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-envelope">Buscar Solicitantes</span></a></li>
                </ul>
            </nav>

        </div>

        <div class="bottom">

            <!-- Social Icons -->
            <ul class="icons">
                <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
                <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
                <li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
                <li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
                <li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
            </ul>

        </div>

    </div>


    <section id="main_s">
        @RenderBody()
    </section>

    <!-- Footer -->
    <div id="footer">

        <!-- Copyright -->
        <ul class="copyright">
            <li>&copy; Untitled. All rights reserved.</li>
            <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
        </ul>

    </div>


    @Scripts.Render("~/bundles/js/dbs")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

SiteProfss_v01/Views/dbd_Empresa/_NomEmpresaPartial.cshtml
@model SiteProfss_v01.Models.DB.Empresa

<!-- Logo -->
<div id="logo">
    <span class="image avatar48"><img src="~/img/avatar.jpg" alt="" /></span>
    <h1 id="title">@Model.NombreEmpresa</h1>
    <p>@Model.Email</p>
</div>