SiteProfss_v01/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteProfss_v01.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult ListarOfertas()
        {
            return View();
        }
    }
}

SiteProfss_v01/Controllers/SolicitantesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiteProfss_v01.Models.Clases;
using SiteProfss_v01.Models.DB;
using SiteProfss_v01.Models;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace SiteProfss_v01.Controllers
{
    public class SolicitantesController : Controller
    {
        private DB_SiteProfss db = new DB_SiteProfss();
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        // GET: Solicitantes
        public ActionResult Index()
        {
            var lstUsuarios = db.Usuarios.ToList();
           
            var lstSolicitantes = new List<Solicitante>();

            foreach (Usuario u in lstUsuarios)
            {
                try
                {
                    lstSolicitantes.Add((Solicitante)u);
                }
                catch (InvalidCastException)
                {
                    continue;
                }
                
            }

            return View(lstSolicitantes);
        }

        // GET: Solicitantes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solicitante eSolicitante = (Solicitante)db.Usuarios.Find(id);
            if (eSolicitante == null)
            {
                return HttpNotFound();
            }
            return View(eSolicitante);
        }

        // GET: Solicitantes/Create
        public ActionResult Create()
        {
            ViewBag.AnioAcademicoId = new SelectList(db.AniosAcademicos, "Id", "Descripcion", "Selecccionar");
            ViewBag.SexoId = new SelectList(db.Sexos, "Id", "Descripcion", "Selecccionar");
            return View();
        }

        // POST: Solicitantes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id, NumeroCedula, Email,Password,ConfirmPassword,Nombres,Apellidos, SexoId, FechaNacimiento, AnioAcademicoId")] vmSolicitante eSolicitante)
        {
            if (ModelState.IsValid)
            {
                Solicitante oSlct = new Solicitante
                {
                    NumeroCedula = eSolicitante.NumeroCedula,
                    Nombres = eSolicitante.Nombres,
                    Apellidos = eSolicitante.Apellidos,
                    SexoId = eSolicitante.SexoId,
                    FechaNacimiento = eSolicitante.FechaNacimiento,
                    AnioAcademicoId = eSolicitante.AnioAcademicoId,
                    Email = eSolicitante.Email,
                    Password = eSolicitante.Password,
                };

                db.Usuarios.Add(oSlct);
                db.SaveChanges();   

                await Registrar(oSlct);

                return RedirectToAction("Index");

            }

            ViewBag.AnioAcademicoId = new SelectList(db.AniosAcademicos, "Id", "Descripcion", eSolicitante.AnioAcademicoId);
            ViewBag.SexoId = new SelectList(db.Sexos, "Id", "Descripcion", eSolicitante.SexoId);
            return View(eSolicitante);
        }

        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Registrar(Solicitante pUsuario)
        {
            if (ModelState.IsValid)
            {
                var Usuario = new ApplicationUser { UserName = pUsuario.Email, Email = pUsuario.Email };
                var result = await UserManager.CreateAsync(Usuario, pUsuario.Password);
                if (result.Succeeded)
                {
                    await SignInManager.SignInAsync(Usuario, isPersistent: false, rememberBrowser: false);

                    return RedirectToAction("Index", "Home");
                }
                AddErrors(result);
            }

            // Si llegamos a este punto, es que se ha producido un error y volvemos a mostrar el formulario
            return View(pUsuario);
        }



        // GET: Solicitantes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solicitante eSolicitante = (Solicitante)db.Usuarios.Find(id);
            if (eSolicitante == null)
            {
                return HttpNotFound();
            }
            ViewBag.AnioAcademicoId = new SelectList(db.AniosAcademicos, "Id", "Descripcion", eSolicitante.AnioAcademicoId);
            ViewBag.SexoId = new SelectList(db.Sexos, "Id", "Descripcion", eSolicitante.SexoId);
            return View(eSolicitante);
        }

        // POST: Solicitantes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,Password,ConfirmPassword,Nombres,Apellidos,SexoId,AnioAcademicoId")] Solicitante eSolicitante)
        {
            if (ModelState.IsValid)
            {
                eSolicitante.Email = eSolicitante.Email;
                eSolicitante.Password = eSolicitante.Password;
                eSolicitante.Nombres = eSolicitante.Nombres;
                eSolicitante.Apellidos = eSolicitante.Apellidos;
                eSolicitante.SexoId = eSolicitante.SexoId;
                eSolicitante.AnioAcademicoId = eSolicitante.AnioAcademicoId;

                db.Entry(eSolicitante).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AnioAcademicoId = new SelectList(db.AniosAcademicos, "Id", "Codigo", eSolicitante.AnioAcademicoId);
            ViewBag.SexoId = new SelectList(db.Sexos, "Id", "Codigo", eSolicitante.SexoId);
            return View(eSolicitante);
        }

        //GET: Solicitantes/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    eSolicitante eSolicitante = db.eSolicitantes.Find(id);
        //    if (eSolicitante == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(eSolicitante);
        //}

        //POST: Solicitantes/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    eSolicitante eSolicitante = db.eSolicitantes.Find(id);
        //    db.eSolicitantes.Remove(eSolicitante);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SiteProfss_v01/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}


<div class="col-md-12">
    <div class="about-area">
        <div class="row">
            <div class="col-md-5 col-sm-6 col-xs-12">
                <div class="about-left wow fadeInLeft">
                    <img src="/img/site-img11.jpg" alt="img" width="495px" height="410px">
                    <a class="introduction-btn" href="#">Nosotros</a>
                </div>
            </div>
            <div class="col-md-7 col-sm-6 col-xs-12">
                <div class="about-right wow fadeInRight">
                    <div class="title-area">
                        <h2 class="tittle">Aceca de <span>SiteProfss</span> </h2>
                        <span class="tittle-line"></span>
                        <span class="title-about">
                            <p>
                                Nuestro principal objetivo es entregar a la comunidad universitaria la oportunidad de llevar a cabo sus prácticas universitarias, disminuyendo las limitantes que puedan dificultar o impedir la realización; garantizando un canal directo entre los estudiantes con las empresas del pais formando una comunidad de empresas que brinden oportunidades a los usuarios de esta aplicación y con ello puedan obtener el fácil acceso a la información de búsqueda que se apegue a su perfil académico.
                            </p>
                        </span>
                        <div class="about-btn-area">
                            <a href=@Url.Action("Create", "Solicitantes") class="button button-default" data-text="SITEPROFSS"><span>REGISTRATE</span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SiteProfss_v01/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<!-- Start Contact section -->
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="contact-left wow fadeInLeft">
                    <h2>Contactanos</h2>
                    <address style="font-family: 'Segoe UI';" class="single-address">
                        <h4 style="text-align:left;">Dirección:</h4>
                        <p>Recinto Universitario "Rubén Darío"De Enel Central 2 Km al Sur Managua</p>
                    </address>
                    <address style="font-family: 'Segoe UI'" class=" single-address">
                        <h4 style="text-align:left;">  Headquarters:</h4>
                        <p>121 King Street, Melbourne Victoria 3000 Australia</p>
                    </address>
                    <address style="font-family: 'Segoe UI'; " class=" single-address">
                        <h4 style="text-align:left;">Telefonos</h4>
                        <p>Numeros de Telefonos: (505) 87145821</p>
                    </address>
                    <address style="font-family: 'Segoe UI'; " class="single-address">
                        <h4 style="text-align:left;">E-Mail</h4>
                        <p>michael.va81952@gmail.com</p>
                        <p>sales@example.com</p>
                    </address>
                </div>
            </div>
            <div class="col-md-8 col-sm-6 col-xs-12">
                <div class="contact-right wow fadeInRight">
                    <h2>Envianos un mensaje</h2>
                    <form action="" class="contact-form">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Nombre">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Ingresa tu Email">
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" placeholder="Ingresa tu comentario"></textarea>
                        </div>
                        <button type="submit" data-text="¡AHORA!" class="button button-default"><span>ENVIAR</span></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Contact section -->
<!-- Start Google Map -->
<section id="google-map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3901.0960797412154!2d-86.27374648518685!3d12.105574691428174!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8f715590dd6ce7a9%3A0xedbc07cfd988036c!2sUniversidad+Nacional+Aut%C3%B3noma+de+Nicaragua!5e0!3m2!1ses!2s!4v1476217574016" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</section>